### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by MatteoGabriele** [Blocklevel/blue-next#2]
### Goal
Running `bcli build` should start a build process based on provided options

### Description
the build process should bundle the project ready for production

Should be possible to 
- [ ] Change global configuration based on environment (i.e. prod, dev or uat )
- [x] Optimize images, css and javascript file
- [x] Choose where to drop the build
- [x] Create a versioned build (?)
- [x] Tree shaking 
- [x] Extract CSS

**Comment by jonaskuiler** [comment]
**Run a build for different environment:**
I've thought about this and running builds in different environments shouldn't be necessary. We can do all configuration in run-time for things like API endpoints, API keys, debug modes etc. The only thing that needs to be embedded in the build is the name of the environment (`NODE_ENV`).

That way we can split up the build config into a local and production version.

**Choose where to drop the build:**
I'm planning to add support for post build hooks which will be located in the project itself, this should solve the problem on where to drop the build. 

**Create a versioned build:**
We can also prevent caching with a cache bust url (append the url to a static file with ?v1.0.0) since we never roll back to a specific version. When needed, this can also be done in a post build hook.

**Comment by MatteoGabriele** [comment]
We don't really need to split the configuration, if we use the config file of the project, we can decide in runtime what will be and where.
Different public path, different location of the build and things like this.

`bcli.config.js`
```js
export default {
  title: 'my project',
  settings: {
    env: [
      {
        name: 'prod',
        publicPath: '/'
      }
    ]
  }
}
```

**Comment by MatteoGabriele** [comment]
added hashed build 
see cba71ce87a16a000102495557c64352e565d8a80
